name: Max Fleetwood
favicon: null
layout_spectrum: 0.74373
typography_spectrum: 0.76794
title: mxfltwd
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#132620'
    - '#a27a60'
    - '#c3af97'
    - '#485d62'
    - '#758e8a'
  brandStrength: 1
  lightness: 0.1326775043271482
  saturation: 0.8125
  rhythmicContrast: 0.06503525958396494
purpose: []
